# Generated by Django 3.0.3 on 2020-05-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20200508_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='memberships',
            new_name='membership',
        ),
    ]
