# Generated by Django 3.0.3 on 2020-05-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20200509_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='stripe_plan_id',
            field=models.CharField(max_length=43),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.Membership'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='stripe_customer_id',
            field=models.CharField(max_length=43),
        ),
    ]
